apiVersion: v1
kind: ConfigMap
metadata:
  name: lakevision-config

data:
  PYICEBERG_CATALOG__DEFAULT__URI: ""
  PYICEBERG_CATALOG__DEFAULT__WAREHOUSE: ""
  PYICEBERG_CATALOG__DEFAULT__S3__ENDPOINT: ""
  GCP_KEYFILE: ""
  PYICEBERG_CATALOG__GCS__PROJECT_ID: ""
  PYICEBERG_CATALOG__GCS__DEFAULT_BUCKET_LOCATION: ""
  AUTHZ_MODULE_NAME: ""
  AUTHZ_CLASS_NAME: ""
  PUBLIC_AUTH_ENABLED: "false"
  PUBLIC_OPENID_CLIENT_ID: ""
  PUBLIC_OPENID_PROVIDER_URL: ""
  PUBLIC_REDIRECT_URI: ""
  PUBLIC_COMPANY_NAME: "Apache Iceberg"
  PUBLIC_PLATFORM_NAME: "Lakehouse"
  PUBLIC_EXTRA_LINK: ""
  PUBLIC_EXTRA_LINK_TEXT: ""
  PUBLIC_API_SERVER_SERVER_SIDE: 'http://localhost:8000'