apiVersion: v1
kind: Secret
metadata:
  name: lakevision-secrets

type: Opaque
stringData:
  PYICEBERG_CATALOG__DEFAULT__TOKEN: ""
  PYICEBERG_CATALOG__DEFAULT__S3__ACCESS_KEY_ID: ""
  PYICEBERG_CATALOG__DEFAULT__S3__SECRET_ACCESS_KEY: ""
  OPEN_ID_CLIENT_SECRET: ""